### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by tsYaroslav** [tsYaroslav/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by svedd121** [comment]
Here it is, a compilation of funny moments in a video down below:
`<iframe width="1280" height="720" src="https://www.youtube.com/embed/t-lMIGV-dUI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Comment by tsYaroslav** [comment]
@svedd121  Can u add some additional info?

**Comment by svedd121** [comment]
Personal life & and funny moments
He is married to Anjali Pichai, née Haryani, a chemical engineer from Kota, Rajasthan. They met as classmates at the Indian Institute of Technology Kharagpur. The couple have two children. Pichai's interests include football and cricket.
Here it is, a compilation of funny moments in a video down below:
`<iframe width="1280" height="720" src="https://www.youtube.com/embed/t-lMIGV-dUI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Comment by tsYaroslav** [comment]
@svedd121 Ok, that's great! Thx!

**Comment by svedd121** [comment]
> @svedd121 Ok, that's great! Thx!

Sure!
