### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by tsYaroslav** [tsYaroslav/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by tsYaroslav** [comment]
sdfsdfsd

**Comment by svedd121** [comment]
“As a leader, it is important to not just see your success but focus on the success of others.” Out of all quotes by Sundar Pichai, this quote reflects his humbleness and vision. Selfishness might help you to become the winner but only compassion can make you into a good leader. Everyone is capable of growing alone. But in the end, the one who is remembered forever is the one who helped others to grow.
